### ISSUE TITLE
Issue with uweng_cropped_6.png

### ISSUE THREAD

**Issue by Shreyas15srivatsa** [yqh/ece252#4]
The uweng_cropped_6.png should be 1000 x 40. However, the png file provided in the Lab1 Starter is 1000 x 22.

**Comment by yqh** [comment]
Each image segment that catpng takes has the same width, but not necessarily the same height (see page 12 of the lab manual). The uweng_cropped_6.png has a different height than other uweng-cropped_[1-5].png for you to test whether the catpng can handle different height image segments.
